//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public Nullable<int> ReferenceToID { get; set; }
    
        public virtual Chemist Chemist { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Physician Physician { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
